from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.entities import Cliente


class IClienteRepository(Protocol):
    def add(self, c: Cliente) -> Cliente: ...
    def update(self, c: Cliente) -> Cliente: ...
    def get_by_id(self, id: int) -> Optional[Cliente]: ...
    def listar(self) -> List[Cliente]: ...
    def delete(self, id: int) -> None: ...
