from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.entities import OrdemServico


class IOrdemServicoRepository(Protocol):
    def add(self, o: OrdemServico) -> OrdemServico: ...
    def update(self, o: OrdemServico) -> OrdemServico: ...
    def get_by_id(self, id: int) -> Optional[OrdemServico]: ...
    def listar(self) -> List[OrdemServico]: ...
