from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.entities import Peca


class IPecaRepository(Protocol):
    def add(self, p: Peca) -> Peca: ...
    def update(self, p: Peca) -> Peca: ...
    def get_by_id(self, id: int) -> Optional[Peca]: ...
    def listar(self) -> List[Peca]: ...
    def listar_por_ids(self, ids: List[int]) -> List[Peca]: ...
    def delete(self, id: int) -> None: ...
