from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.entities import ServicoOficina


class IServicoOficinaRepository(Protocol):
    def add(self, s: ServicoOficina) -> ServicoOficina: ...
    def update(self, s: ServicoOficina) -> ServicoOficina: ...
    def get_by_id(self, id: int) -> Optional[ServicoOficina]: ...
    def listar(self) -> List[ServicoOficina]: ...
    def delete(self, id: int) -> None: ...
