from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.entities import Veiculo


class IVeiculoRepository(Protocol):
    def add(self, v: Veiculo) -> Veiculo: ...
    def update(self, v: Veiculo) -> Veiculo: ...
    def get_by_id(self, id: int) -> Optional[Veiculo]: ...
    def listar_por_cliente(self, cliente_id: int) -> List[Veiculo]: ...
    def listar(self) -> List[Veiculo]: ...
    def delete(self, id: int) -> None: ...
